### ISSUE TITLE
Extrae constantes

### ISSUE THREAD

**Issue by lmagarin** [iesgrancapitan-dwec/Buscaminas-Guillermo#5]
https://github.com/iesgrancapitan-dwec/Buscaminas-Guillermo/blob/f5789bb4729caa5058672812fb83aa97d92d15d9/js/main.js#L207

**Comment by lmagarin** [comment]
No veo las constantes en el commit

**Comment by gboquizo** [comment]
Estaban en el commit 412cc3a179fc79b3d9f3b900ae4abd75b236d42a, las modificaciones posteriores lo dejan atrás

**Comment by gboquizo** [comment]
Y en el commit 18f922de3c927974ac179f0a00f5b617facc8c74, que es el que cerraba este issue, están aquí:

![imagen](https://user-images.githubusercontent.com/25690209/53987199-a2f16a00-4120-11e9-981d-e680291ff880.png)

![imagen](https://user-images.githubusercontent.com/25690209/53987244-bef50b80-4120-11e9-9b1b-4b1dd04dbfaa.png)
