### ISSUE TITLE
Extrae método juegoFinalizado()?

### ISSUE THREAD

**Issue by lmagarin** [iesgrancapitan-dwec/Buscaminas-Guillermo#6]
https://github.com/iesgrancapitan-dwec/Buscaminas-Guillermo/blob/f5789bb4729caa5058672812fb83aa97d92d15d9/js/main.js#L288

**Comment by gboquizo** [comment]
https://github.com/iesgrancapitan-dwec/Buscaminas-Guillermo/blob/dfa31395a299f086b63cb3f226176f9d73edabcd/js/main.js#L597
